name: deep_dog_breeds-env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - mkl
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - pytorch==1.3.0
  - torchvision==0.4.1
  - opencv-python
  - imageio
  - requests
  - pip:
    - tqdm
    - gpustat
    - sklearn